name: Simple Example

on: [push]

jobs:
  demo:

    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Run Echo command
        run: echo "Hello World"

      - name: Run ls command
        run: ls -l

